function [png] = PDF_IMC()

png.PN_name = 'IMC';                % NAME OF THE MODULE
png.set_of_Ps = {'pBeforeTravel', 'pAfterTravel' 'pFinished'};        % SET OF PLACES
png.set_of_Ts = {'tTempoaryTrans'};                 % SET OF TRANSITIONS, this will be replaced with a module later.

% SET OF ARCS
png.set_of_As = {'pBeforeTravel', 'tTempoaryTrans', 1, 'tTempoaryTrans', 'pAfterTravel', 1,...
                 'tOUT','pBeforeTravel',1, 'pAfterTravel', 'tPaintingIn', 1, ...
                'tPaintingOut', 'pBeforeTravel', 1, 'pAfterTravel', 'tInFailCheck', 1, ...
                'pAfterTravel', 'tCreateWheelsIn', 1, 'tCreateWheelsOut', 'pBeforeTravel', 1, ...
                'pAfterTravel', 'tCreateGlassIn', 1, 'tCreateGlassOut', 'pBeforeTravel', 1, ...
                'pAfterTravel', 'tBottomMoldIn', 1, 'tBottomMoldOut', 'pBeforeTravel', 1, ...
                'tOutFailCheck', 'pFinished', 1};
