function [png] = combiner_pdf()

    png.PN_name = 'Combiner';

    png.set_of_Ps = {'pStart1', 'raw1', 'finished1', 'pEnd1', ...
                     'pStart2', 'raw2', 'finished2', 'pEnd2', ...
                     'pOccupied1', 'pOccupied2', 'pJoin'};

    png.set_of_Ts = {'tIN1', 'tIN2', 'tOUT', ...
                     'tStart1ToRaw1', 'tRaw1ToFinished1', 'tFinished1ToEnd1', 'tJoin', ...
                     'tStart2ToRaw2', 'tRaw2ToFinished2', 'tFinished2ToEnd2'};

    png.set_of_As = {'tIN1', 'pStart1', 1, ...
                     'pStart1', 'tStart1ToRaw1', 1, 'pOccupied1', 'tStart1ToRaw1', 1, ...
                     'tStart1ToRaw1', 'raw1', 1, ...
                     'raw1', 'tRaw1ToFinished1', 1, ...
                     'tRaw1ToFinished1', 'finished1', 1, ...
                     'finished1', 'tFinished1ToEnd1', 1, 'tFinished1ToEnd1', 'pOccupied1', 1, ...
                     'tFinished1ToEnd1', 'pEnd1', 1, ...
                     'pEnd1', 'tJoin', 1, ...
                     'tJoin', 'pJoin', 1, ...
                     'tIN2', 'pStart2', 1, ...
                     'pStart2', 'tStart2ToRaw2', 1, 'pOccupied2', 'tStart2ToRaw2', 1, ...
                     'tStart2ToRaw2', 'raw2', 1, ...
                     'raw2', 'tRaw2ToFinished2', 1, ...
                     'tRaw2ToFinished2', 'finished2', 1, ...
                     'finished2', 'tFinished2ToEnd2', 1, 'tFinished2ToEnd2', 'pOccupied2', 1, ...
                     'tFinished2ToEnd2', 'pEnd2', 1, ...
                     'pEnd2', 'tJoin', 1, ...
                     'tJoin', 'pJoin', 1, ...
                     'pJoin', 'tOUT', 1};

    png.set_of_Ports = {'tIN1', 'tIN2', 'tOUT'};
end
