function [png] = agv_pdf()

    png.PN_name = 'AGV';

    png.set_of_Ps = {'pAGVPickup', 'pMoving', 'pAGVDropoff' ...
        'pUnloadedAGV', 'pAGVIdle', 'pAGVGarage'}; 

    png.set_of_Ts = {'tLoadAGV', 'tMove', 'tUnloadAGV', ...
        'tSpawnAGV', 'tAGVIn', 'tAGVOut', 'tAGVToCharging', ...
        'tAGVFromCharging', 'tToIdle'} ;

    png.set_of_Ports = {'tAGVIn', 'tAGVOut', 'tAGVToCharging', ...
        'tAGVFromCharging'};

    png.set_of_As = {
        'tAGVIn', 'pAGVPickup', 1, ...
        'pAGVPickup', 'tLoadAGV', 1, 'tLoadAGV', 'pMoving', 1, ...
        'pMoving', 'tMove', 1, 'tMove', 'pMoving', 1, ... % Loopback to pMoving indicating continuous movement
        'pMoving', 'tUnloadAGV', 1, 'tUnloadAGV', 'pAGVDropoff', 1, ...
        'tUnloadAGV', 'pUnloadedAGV', 1, ...
        'pAGVDropoff', 'tAGVOut', 1,...
        'pAGVGarage', 'tSpawnAGV', 1, 'tSpawnAGV', 'pAGVIdle', 1,...
        'tAGVFromCharging', 'pAGVIdle', 1, ...
        'pAGVIdle', 'tLoadAGV', 1,...
        'pUnloadedAGV', 'tAGVToCharging', 1,...
        'pUnloadedAGV', 'tToIdle', 1, 'tToIdle', 'pAGVIdle', 1};
    