function [png] = robot_cnc_pdf()

    png.PN_name = 'Robot CNC operator';

    png.set_of_Ps = {'pMagazine', 'pCNC1Raw', 'pCNC2Raw', 'pCNC1Finished', 'pCNC2Finished', 'pDeliveryBox', 'pCNC1Occupied', 'pCNC2Occupied'};
    
    png.set_of_Ts = {'tCNCIn', 'tCNCOut'  'tMagazineToCNC1Raw', 'tMagazineToCNC2Raw', 'tCNC1RawToCNC1Finished', 'tCNC2RawToCNC2Finished', 'tCNC1FinishedToDeliveryBox', 'tCNC2FinishedToDeliveryBox'};

    png.set_of_As = {'tCNCIn', 'pMagazine', 1, ...
                     'pMagazine', 'tMagazineToCNC1Raw', 1, 'pCNC1Occupied', 'tMagazineToCNC1Raw', 1, 'tMagazineToCNC1Raw', 'pCNC1Raw', 1, ...
                     'pMagazine', 'tMagazineToCNC2Raw', 1, 'pCNC2Occupied', 'tMagazineToCNC2Raw', 1, 'tMagazineToCNC2Raw', 'pCNC2Raw', 1, ...
                     'pCNC1Raw', 'tCNC1RawToCNC1Finished', 1, 'tCNC1RawToCNC1Finished', 'pCNC1Finished', 1,...
                     'pCNC2Raw', 'tCNC2RawToCNC2Finished', 1, 'tCNC2RawToCNC2Finished', 'pCNC2Finished', 1,...
                     'pCNC1Finished', 'tCNC1FinishedToDeliveryBox', 1, 'tCNC1FinishedToDeliveryBox', 'pDeliveryBox', 1, 'tCNC1FinishedToDeliveryBox', 'pCNC1Occupied', 1,  ...
                     'pCNC2Finished', 'tCNC2FinishedToDeliveryBox', 1, 'tCNC2FinishedToDeliveryBox', 'pDeliveryBox', 1, 'tCNC2FinishedToDeliveryBox', 'pCNC2Occupied', 1, ...
                     'pDeliveryBox', 'tCNCOut', 1};
    
    png.set_of_Ports = {'tCNCIn', 'tCNCOut'};
end
